basePath: /api/v1
definitions:
  controllers.healthResponse:
    properties:
      message:
        example: ok
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: jaybhogayata53@gmail.com
    name: Jay Bhogayata
  description: This is a sample server for product-service.
  termsOfService: https://github.com/jay-bhogayata/product-service
  title: product-service API
  version: 0.0.1
paths:
  /health:
    get:
      description: Health check endpoint
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.healthResponse'
      summary: Health check endpoint
      tags:
      - health
schemes:
- http
swagger: "2.0"
